# PR/Main build
name: PR Build
pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    displayName: Verify Code Formatting
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'verifyGoogleJavaFormat'
  - task: Gradle@2
    displayName: Gradle Check Task
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'check'
