name: Snyk Vulnerability Scan
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: deleonenriqueta/dropwizard-metrics-newrelic
          ref: 'main'
          path: dropwizard-metrics-newrelic

      - name: Set gradle.properties
        run: |
          cd ${GITHUB_WORKSPACE}/dropwizard-metrics-newrelic
          sed -i -e "s|jdk8=8|jdk8=${JAVA_HOME_8_x64}|
          s|jdk11=11|jdk11=${JAVA_HOME_11_x64}|
          s|jdk17=17|jdk17=${JAVA_HOME_17_x64}|" gradle.properties.gha
          cat gradle.properties.gha >> gradle.properties

      - name: Setup Gradle Options
        run: echo "GRADLE_OPTIONS=-Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME_17_x64,JAVA_HOME_11_x64,JAVA_HOME_8_x64" >> $GITHUB_ENV
          
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Run Snyk Vulnerability Scan
        uses: snyk/actions/gradle@master
        with:
          args: --all-sub-projects --command=test
          # args: --all-sub-projects --command=monitor --org=java-agent
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}







